CC	= gcc
CFLAGS	= -O2 -DTISL_C -DTISL_TEST

OBJ	= built_in_object.o evaluator.o gc.o\
	  object.o object_2.o object_3.o operation.o\
	  operation_2.o reader.o primitive_operation.o\
	  tisl.o tni.o translator.o translator_1.o translator_2.o\
	  vm.o writer.o interpreter.o

tisl_obj : $(OBJ)
